### ISSUE TITLE
Loader must implement addPlugin(pluginName, implementation)

### ISSUE THREAD

**Issue by mmalek06** [grofit/aurelia-chart#19]
As soon as I installed aurelia-chart and bundled my application I got the above error in the console. I'm using Aureliajs v1, so probably some update for the plugin is needed.

**Comment by grofit** [comment]
lol when isn't there an update needed for aurelia, not a clue about that one hopefully someone else can provide you some information on what is missing or needed, if you can provide information on:
- How you are resolving your dependencies? (i.e JSPM, NPM etc)
- How you are bundling? (Webpack, JSPM, Aurelia CLI etc)
- Actual Error message output.

**Comment by mmalek06** [comment]
I'm using JSPM to bundle and resolve. Actual message output is this:

aurelia.js:15 Uncaught (in promise) Error: Loader must implement addPlugin(pluginName, implementation).
    at a.Loader.a.addPlugin (http://localhost:9000/dist/aurelia.js:15:31664)
    at a.ViewEngine.a.addResourcePlugin (http://localhost:9000/dist/aurelia.js:20:14418)
    at e (http://localhost:9000/dist/aurelia.js:15:8497)
    at r.E (http://localhost:9000/dist/aurelia.js:15:21214)
    at eval (http://localhost:9000/dist/aurelia.js:13:12452)a.Loader.a.addPlugin @ aurelia.js:15a.ViewEngine.a.addResourcePlugin @ aurelia.js:20e @ aurelia.js:15E @ aurelia.js:15(anonymous function) @ aurelia.js:13

**Comment by grofit** [comment]
and can you show us the code you are using to include the plugin in aurelia?

**Comment by mmalek06** [comment]
It's just a standard use.plugin("aurelia-chart") call. 
I think I figured out why it's not working. It has something to do with aurelia fw version, but in a different way I initially thought. I'm using v.1.0.0-rc6, not 1.0.0. Installing this plugin caused whole aurelia components set to upgrade and probably one of those components (in the new version) is buggy and it's not yours :). Don't have time right now to investigate any further unfortunatelly :(

**Comment by grofit** [comment]
No worries if you solve it just update this so others know what to do.

**Comment by mmalek06** [comment]
Dunno what happened. I removed my project, cloned it from git, installed all the dependencies, then the aurelia-chart plugin and everything seems to work even though lots of packages were updated after installing this plugin. I probably messed something up badly prior to installing aurelia chart. Anysways - please close or remove this issue as there is and was no bug here :)

**Comment by grofit** [comment]
no problem, glad its all working.
