### ISSUE TITLE
Two-way binding on native options

### ISSUE THREAD

**Issue by rmja** [grofit/aurelia-chart#22]
To allow accessing and overwriting native options after the chart is attached, it would be nice if the nativeOptions was default two-way bound (`@bindable({defaultBindingMode: bindingMode.twoWay})`), and in `createChart()` the active chart options was written back to the nativeOptions property:

```
createChart() {
    this._chartData = {
      type: this.type,
      data: this._clonedData,
      options: this._clonedNativeOptions
    };

    this._activeChart = new Chart(this.canvasElement, this._chartData);
    this.refreshChart();

    this.nativeOptions = this._activeChart.options;
  };
```

**Comment by grofit** [comment]
If you know how you want it to work by all means raise a PR for it, I am happy for any PRs as long as new features do not break normal use-cases.
