### ISSUE TITLE
should-update="true" working again?

### ISSUE THREAD

**Issue by KarstenHoehne** [grofit/aurelia-chart#29]
In the DOC under Usage it says:

> Or you can tell it to listen to observable changes: (Not working due to re-structuring of aurelia bindings atm)
> 
> <chart type="pie" data.bind="myData" should-update="true" throttle="100"></chart>

is that still the case or was this fixed (and the DOC simply not updated)? Is there a workaround?

**Comment by grofit** [comment]
Looking through the source it looks like `ModelObserver` was added so I assume it works and the example seems to update when you change values.

The original problem was that historically Aurelia didn't have a consistent way to "subscribe" to variables in a browser/platform agnostic way, so without being able to subscribe to the data changes I couldn't work out that stuff needed to update (unless I wrote some dirty checker or something).

So it should probably just be a doc update, however this plugin was originally created A LONG time ago in the early days of Aurelia and I dont do much with Aurelia currently so it is not really maintained, but it should work ok, as the examples run.

**Comment by KarstenHoehne** [comment]
cool thank you for the quick response

**Comment by grofit** [comment]
Have updated the docs to remove this, feel free to re-open if you find anything different to what I say above.

**Comment by KarstenHoehne** [comment]
thanks, i will do that
