### ISSUE TITLE
Binding to native-options not working

### ISSUE THREAD

**Issue by Tarpsvo** [grofit/aurelia-chart#32]
Hey.

I am, for some unknown reason, unable to bind to the native-options property.

The most straight forward copied example does not work.

Example used:
`<chart type="pie" data.bind="myData" native-options.bind="{ segmentShowStroke: true, segmentStrokeColor: '#fff', segmentStrokeWidth: 2 }"></chart>`

Error returned:
`Unhandled rejection Error: Binding expression "{'segmentShowStroke':true,'segmentStrokeColor':'#fff','segmentStrokeWidth':2}" cannot be assigned to.`

Some maybe related info:
WebPack 2.3. AureliaWebPackPlugin 2-RC2.

**Comment by grofit** [comment]
do you need the `{` and `}` brackets? it may be an issue with my documentation as it was all written years ago, so it may be a case of the bind does not need the brackets and gets confused with them, if that doesnt work then I am not sure, but it looks like its the core aurelia binding which is confused not the loader or anything.

**Comment by Tarpsvo** [comment]
Binding to an object created inline is not something I could get to work. I just created the object in the view controller and bound to it.
