### ISSUE TITLE
Reanimate Chart without Data Update

### ISSUE THREAD

**Issue by ndzeller** [grofit/aurelia-chart#37]
Is there a way to reanimate the chart based off of an event even if no data is updated?

**Comment by grofit** [comment]
not sure, does ChartJS expose it?

**Comment by ndzeller** [comment]
Sorry :) hit enter before I was done

**Comment by grofit** [comment]
Ah that makes more sense, erm you shoudl be able to basically re-initialize it, as behind the scenes it just listens for changes then I think it destroys and recreates it. So you may be able to expose some sort of hook from the binding/directive to let you manually trigger the recreation logic.

**Comment by ndzeller** [comment]
That worked! Thanks @grofit . When I re-initialized the data it updated as desired.

**Comment by grofit** [comment]
this was the best issue ever then :)

**Comment by ndzeller** [comment]
Agreed :) thanks for creating aurelia-chart!
