### ISSUE TITLE
0.3.3 has got only 2 files released

### ISSUE THREAD

**Issue by MaximBalaganskiy** [grofit/aurelia-chart#45]
🙃

**Comment by grofit** [comment]
not a clue buddy I just pulled and ran the npm stuff like last time which did the release

**Comment by MaximBalaganskiy** [comment]
I’ll check the scripts

**Comment by grofit** [comment]
ive done another `npm run build` and `npm run publish:latest` if its not working this time on 0.3.4 the build stuff will need checking.
