### ISSUE TITLE
Add Collaborators?

### ISSUE THREAD

**Issue by grofit** [grofit/aurelia-chart#60]
@MaximBalaganskiy over the years you have been more active in adding and maintaining stuff to do with this repository, as I no longer really support it unless there is something SUPER urgent would you be ok if I added you as a collaborator on here to assist in maintaining this repo without me and possibly adding you as a collaborator on npm so you can push out new versions if needed.

As mentioned before I realistically don't do anything Aurelia related these days so while PRs are welcome they rarely go to npm unless someone yells at me loud enough, which isnt much help to anyone 😄

**Comment by MaximBalaganskiy** [comment]
Sure, I don't mind. There's little maintenance anyway - just upgrade versions occasionally

**Comment by grofit** [comment]
I dont know of a way to pm on here but if you can tell me your npm username I can add you on there too so you can do npm deployments for the package if you want, save you having to ask me to do it 😄 

Or if you are feeling adventurous feel free to setup a github action to pump it out to there automatically (historically I just built and pushed it to npm locally)

**Comment by MaximBalaganskiy** [comment]
It's m.balaganskiy

**Comment by grofit** [comment]
All done, thanks for your help
